namespace WinForms
{

    public partial class SelectionBoxes : Form
    {
        public SelectionBoxes()
        {
            InitializeComponent();
        }

        /** Generated by C# Design Editor */
        private void InitializeComponent()
        {
            radioButton1 = new RadioButton();
            listView1 = new ListView();
            radioButton2 = new RadioButton();
            radioButton3 = new RadioButton();
            checkBox1 = new CheckBox();
            checkBox2 = new CheckBox();
            checkBox3 = new CheckBox();
            label1 = new Label();
            label2 = new Label();
            label3 = new Label();
            button1 = new Button();
            button2 = new Button();
            SuspendLayout();
            // 
            // radioButton1
            // 
            radioButton1.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            radioButton1.AutoSize = true;
            radioButton1.Location = new Point(33, 72);
            radioButton1.Name = "radioButton1";
            radioButton1.Size = new Size(45, 19);
            radioButton1.TabIndex = 0;
            radioButton1.TabStop = true;
            radioButton1.Text = "Red";
            radioButton1.UseVisualStyleBackColor = true;
            radioButton1.CheckedChanged += radioButton1_CheckedChanged;
            // 
            // listView1
            // 
            listView1.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            listView1.Location = new Point(467, 33);
            listView1.Name = "listView1";
            listView1.Size = new Size(222, 286);
            listView1.TabIndex = 1;
            listView1.UseCompatibleStateImageBehavior = false;
            listView1.SelectedIndexChanged += listView1_SelectedIndexChanged;
            // 
            // radioButton2
            // 
            radioButton2.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            radioButton2.AutoSize = true;
            radioButton2.Location = new Point(33, 97);
            radioButton2.Name = "radioButton2";
            radioButton2.Size = new Size(56, 19);
            radioButton2.TabIndex = 2;
            radioButton2.TabStop = true;
            radioButton2.Text = "Green";
            radioButton2.UseVisualStyleBackColor = true;
            radioButton2.CheckedChanged += radioButton2_CheckedChanged;
            // 
            // radioButton3
            // 
            radioButton3.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            radioButton3.AutoSize = true;
            radioButton3.Location = new Point(33, 122);
            radioButton3.Name = "radioButton3";
            radioButton3.Size = new Size(48, 19);
            radioButton3.TabIndex = 3;
            radioButton3.TabStop = true;
            radioButton3.Text = "Blue";
            radioButton3.UseVisualStyleBackColor = true;
            radioButton3.CheckedChanged += radioButton3_CheckedChanged;
            // 
            // checkBox1
            // 
            checkBox1.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            checkBox1.AutoSize = true;
            checkBox1.Location = new Point(30, 231);
            checkBox1.Name = "checkBox1";
            checkBox1.Size = new Size(48, 19);
            checkBox1.TabIndex = 4;
            checkBox1.Text = "Dog";
            checkBox1.UseVisualStyleBackColor = true;
            checkBox1.CheckedChanged += checkBox1_CheckedChanged;
            // 
            // checkBox2
            // 
            checkBox2.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            checkBox2.AutoSize = true;
            checkBox2.Location = new Point(30, 256);
            checkBox2.Name = "checkBox2";
            checkBox2.Size = new Size(44, 19);
            checkBox2.TabIndex = 5;
            checkBox2.Text = "Cat";
            checkBox2.UseVisualStyleBackColor = true;
            checkBox2.CheckedChanged += checkBox2_CheckedChanged;
            // 
            // checkBox3
            // 
            checkBox3.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            checkBox3.AutoSize = true;
            checkBox3.Location = new Point(30, 281);
            checkBox3.Name = "checkBox3";
            checkBox3.Size = new Size(47, 19);
            checkBox3.TabIndex = 7;
            checkBox3.Text = "Fish";
            checkBox3.UseVisualStyleBackColor = true;
            checkBox3.CheckedChanged += checkBox3_CheckedChanged;
            // 
            // label1
            // 
            label1.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            label1.AutoSize = true;
            label1.Location = new Point(30, 45);
            label1.Name = "label1";
            label1.Size = new Size(103, 15);
            label1.TabIndex = 8;
            label1.Text = "Background Color";
            label1.Click += label1_Click;
            // 
            // label2
            // 
            label2.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            label2.AutoSize = true;
            label2.Location = new Point(30, 203);
            label2.Name = "label2";
            label2.Size = new Size(79, 15);
            label2.TabIndex = 9;
            label2.Text = "Text Contents";
            label2.Click += label2_Click;
            // 
            // label3
            // 
            label3.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            label3.AutoSize = true;
            label3.Location = new Point(526, 349);
            label3.Name = "label3";
            label3.Size = new Size(101, 15);
            label3.TabIndex = 10;
            label3.Text = "Selected: Nothing";
            label3.Click += label3_Click;
            // 
            // button1
            // 
            button1.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            button1.Location = new Point(584, 440);
            button1.Name = "button1";
            button1.Size = new Size(105, 36);
            button1.TabIndex = 12;
            button1.Text = "Load Next Form";
            button1.UseVisualStyleBackColor = true;
            button1.Click += button1_Click;
            // 
            // button2
            // 
            button2.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            button2.Location = new Point(28, 440);
            button2.Name = "button3";
            button2.Size = new Size(105, 36);
            button2.TabIndex = 11;
            button2.Text = "Load Prev Form";
            button2.UseVisualStyleBackColor = true;
            button2.Click += button2_Click;
            // 
            // SelectionBoxes
            // 
            ClientSize = new Size(730, 488);
            Controls.Add(button1);
            Controls.Add(button2);
            Controls.Add(label3);
            Controls.Add(label2);
            Controls.Add(label1);
            Controls.Add(checkBox3);
            Controls.Add(checkBox2);
            Controls.Add(checkBox1);
            Controls.Add(radioButton3);
            Controls.Add(radioButton2);
            Controls.Add(listView1);
            Controls.Add(radioButton1);
            Name = "SelectionBoxes";
            Text = "Selection Boxes";
            Load += SelectionBoxes_Load;
            ResumeLayout(false);
            PerformLayout();
        }

        //BG RED
        private void radioButton1_CheckedChanged(object sender, EventArgs e)
        {
            if (radioButton1.Checked)
            {
                radioButton2.Checked = false;
                radioButton3.Checked = false;
                listView1.BackColor = Color.Red;
                listView1.ForeColor = Color.Black;
            }
        }

        //BG GREEN
        private void radioButton2_CheckedChanged(object sender, EventArgs e)
        {
            if (radioButton2.Checked)
            {
                radioButton1.Checked = false;
                radioButton3.Checked = false;
                listView1.BackColor = Color.Green;
                listView1.ForeColor = Color.White;
            }
        }

        //BG BLUE
        private void radioButton3_CheckedChanged(object sender, EventArgs e)
        {
            if (radioButton3.Checked)
            {
                radioButton1.Checked = false;
                radioButton2.Checked = false;
                listView1.BackColor = Color.Blue;
                listView1.ForeColor = Color.White;
            }
        }

        // Add/Remove DOG
        private void checkBox1_CheckedChanged(object sender, EventArgs e)
        {
            if (checkBox1.Checked)
            {
                dog = listView1.Items.Add("Dog");
            }
            else
            {
                listView1.Items.Remove(dog);
            }
        }

        // Add/Remove CAT
        private void checkBox2_CheckedChanged(object sender, EventArgs e)
        {
            if (checkBox2.Checked)
            {
                cat = listView1.Items.Add("Cat");
            }
            else
            {
                listView1.Items.Remove(cat);
            }
        }

        // Add/Remove FISH
        private void checkBox3_CheckedChanged(object sender, EventArgs e)
        {
            if (checkBox3.Checked)
            {
                fish = listView1.Items.Add("Fish");
            }
            else
            {
                listView1.Items.Remove(fish);
            }
        }

        //load next project (image loading)
        private void button1_Click(object sender, EventArgs e)
        {
            Form3 newForm = new Form3();
            this.Hide();
            newForm.ShowDialog();
        }

        //load previous project (higher or lower)
        private void button2_Click(object sender, EventArgs e)
        {
            Form1 newForm = new Form1();
            this.Hide();
            newForm.ShowDialog();
        }

        /** Update the label to show what is selected on the list view */
        private void listView1_SelectedIndexChanged(object sender, EventArgs e)
        {
            if (listView1.SelectedItems.Count > 0)
            {
                String text = listView1.SelectedItems[0].Text;
                label3.Text = "Selected: " + text;
            }
            else
            {
                label3.Text = "Selected: Nothing";
            }
        }

        private void label1_Click(object sender, EventArgs e)
        {

        }

        private void label2_Click(object sender, EventArgs e)
        {

        }

        private void label3_Click(object sender, EventArgs e)
        {

        }

        private void SelectionBoxes_Load(object sender, EventArgs e)
        {

        }

        private ListView listView1;
        private RadioButton radioButton1;
        private RadioButton radioButton2;
        private RadioButton radioButton3;
        private CheckBox checkBox1;
        private CheckBox checkBox2;
        private CheckBox checkBox3;
        private Label label1;
        private Label label2;
        private Label label3;

        //global to reserve state between updates
        private ListViewItem dog;
        private ListViewItem cat;
        private Button button2;
        private Button button1;
        private ListViewItem fish;
    }
}
